version: "1"
services:
  devkitminimal:
    build:
      args:
        BASE_NAME: continuumio/miniconda3
        BASE_TAG: ${BASE_TAG:-latest}
        CONDA_VERSION: ${BASE_TAG:-23.5.0}
        http_proxy: ${http_proxy}
        HTTP_PROXY: ${HTTP_PROXY}
        https_proxy: ${https_proxy}
        HTTPS_PROXY: ${HTTPS_PROXY}
        o_proxy: ${no_proxy}
        ftp_proxy: ${ftp_proxy}
      context: ../
      dockerfile: docker/Dockerfile
      target: devkitminimal
    image: devkitminimal

  medical-image-diag:
    image: medical-image-diag:latest
    build:
      target: medical-image-diag
    extends:
      service: devkitminimal

  interactive:
    environment:
      - WORKSPACE=${MOUNT_WORKSPACE}
      - DATA_DIR=${MOUNT_DATA_DIR}
      - OUTPUT_DIR=${MOUNT_OUTPUT_DIR}
    extends:
      service: medical-image-diag
    stdin_open: true 
    tty: true
    volumes:
      - "${WORKSPACE}:${MOUNT_WORKSPACE}"
      - "${DATA_DIR}:${MOUNT_DATA_DIR}"
      - "${OUTPUT_DIR}:${MOUNT_OUTPUT_DIR}"